apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
  namespace: default
  labels:
    app: hello-k8s
spec:
  selector:
    app: hello-k8s
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30090
  type: NodePort
